Bump Spotify Polybar module Python dependency to 3.8
The reason for this is as follows (most relevant line appended with `!!!!!!!!` :

error: builder for '/nix/store/0d2zcgaxdmmppbzxgxbgln6kmm8hr692-python3.7-setuptools-scm-7.0.5.drv' failed with exit code 1;
       last 10 log lines:
       > adding 'setuptools_scm-7.0.5.dist-info/RECORD'
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/setuptools_scm-7.0.5/dist /build/setuptools_scm-7.0.5
       > Processing ./setuptools_scm-7.0.5-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement importlib-metadata; python_version < "3.8" (from setuptools-scm) (from versions: none)  !!!!!!!!
       > ERROR: No matching distribution found for importlib-metadata; python_version < "3.8"
       >
       For full logs, run 'nix log /nix/store/0d2zcgaxdmmppbzxgxbgln6kmm8hr692-python3.7-setuptools-scm-7.0.5.drv'.
error: 1 dependencies of derivation '/nix/store/7yvryncl9dnzgqnym391dpqnfyajp87n-python3.7-pytest-7.1.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/a6zm7ccd6gy2plb5kw35rss05i2dfklq-pytest-check-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qfdv1wsyxff8g94m0w1jid7zmwxknfqa-python3.7-pycairo-1.21.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rira3xcg4vq0rqa3r39wgdaxb9yjfwf0-python3.7-pygobject-3.42.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jqbk17rsch4yllwwv1nmwxirfijyy079-python3.7-dbus-python-1.2.18.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0wlxaykwlh5vpadrdyv00q7xxkrdp567-python3-3.7.13-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/69jgb4zx60p8gbh754ihji3q57ab8mw5-polybar.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/a428fdy9r8xs6f7dh9gyh5nbdjvlidhb-home-manager-files.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ssf0nwvikwbcyaxvi7b4alddfk719mwd-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hgz8r9p6y65r4wi2jjb3mssqx3dxnv2b-unit-home-manager-geko.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zik870bvs9ck7r5swzdwisaj791wilcr-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vaaj6mc9rqf6f0fm910qiy03iyvhc5jr-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/67zhsqr0m9cj87c8knx6lqsqkrgskn71-nixos-system-luna-22.11.20220812.c4a0efd.drv' failed to build