deps: update flake inputs
Reasons for non-lockfile changes:

```
       error: 'emacs30-pgtk' has been superseded by 'emacs-pgtk' on august 2026
```

```
       error: 'pinentry-gtk2' has been removed as it depended on the deprecated GTK2 engine, use pinentry-gnome3 instead.
```

```
evaluation warning: geko profile: `programs.ssh.matchBlocks` defined in `/nix/store/cy649f2yb6q0mn1cinsvh5p6dlpa15ln-source/modules/nixos/home' is deprecated. Use `programs.ssh.settings`.
```

```
⛔ Warning (files): Missing ‘lexical-binding’ cookie in "/nix/store/6pnfyhjzmrz3m6nixyvcn4spzfin7nhi-elementary-emacs/share/elementary-emacs/early-init.el".
You can add one with ‘M-x elisp-enable-lexical-binding RET’.
See ‘(elisp)Selecting Lisp Dialect’ and ‘(elisp)Converting to Lexical Binding’
for more information.
⛔ Warning (files): Missing ‘lexical-binding’ cookie in "/nix/store/6pnfyhjzmrz3m6nixyvcn4spzfin7nhi-elementary-emacs/share/elementary-emacs/init.el".
You can add one with ‘M-x elisp-enable-lexical-binding RET’.
See ‘(elisp)Selecting Lisp Dialect’ and ‘(elisp)Converting to Lexical Binding’
for more information.
```

Changed `noshell` input to `codeberg.org`, since viperML moved to
Codeberg (`https://github.com/viperML/noshell/` gives 404).

Also hacks a fix for the minibuffer being stuck in normal mode with evil.

See: https://github.com/emacs-evil/evil/issues/2034